---
title: "rz_snarl_qpcr_comparison"
author: "Cob Staines"
date: "`r Sys.Date()`"
output: html_document
---

# setup
```{r setup, echo=FALSE}
librarian::shelf(tidyverse, dbplyr, here, janitor, rio, RPostgres, DBI, RIBBiTR-BII/ribbitrrr, ggplot2, ggcorrplot)

wddir = here(Sys.getenv("data_dir"), "bd_qpcr_results", "rz_snarl_qpcr_comparison")

dbcon = hopToDB("railway")

```

# load data
```{r load, echo=FALSE}
list.files(wddir)

snarl_raw = import(here(wddir, "qpcr_compare_data_260904.xlsx"),
                   na = c("NA", "NaN"))
rz_raw = import(here(wddir, "RIBBiTR_SierraNevadaComparision_04012026_Plate1_rerun2_Diluted_results.xlsx"),
                which = "WorkingResults")

# pointer tables
db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))

ribbitr_bd = db_bd %>%
  filter(ipc_pass | is.na(ipc_pass)) %>%
  group_by(sample_name_bd) %>%
  mutate(n_results = n()) %>%
  ungroup() %>%
  filter(standard_target_type == "ITS1",
         n_results > 1,
         qpcr_lab %in% c("snarl", "rz_lab")) %>%
  collect()
  
```


```{r clean, echo=FALSE}

rz_snarl_ct = rz_raw %>%
  clean_names() %>%
  rename(bd_swab_id = sample_name) %>%
  mutate(extraction_lab = recode_values(extraction_lab,
                                        "RZ" ~ "rz",
                                        "Sierras" ~ "snarl",
                                        default = NA),
         qpcr_lab = "rz_lab") %>%
  select(bd_swab_id,
         extraction_lab,
         qpcr_lab,
         bd_ct_mean,
         bd_quantity_mean)

snarl_clean = snarl_raw %>%
  clean_names() %>%
  rename(extraction_lab = lab_extract,
         extraction_method = extract_method,
         qpcr_lab = lab_qpcr,
         bd_quant_cycle = quant_cycle,
         bd_start_quant = start_quant) %>%
  mutate(extraction_lab = recode_values(extraction_lab,
                                        "pitt" ~ "rz",
                                        "snarl" ~ "snarl",
                                        default = NA),
         collect_lab = recode_values(collect_lab,
                                     "pitt" ~ "rz",
                                        "snarl" ~ "snarl",
                                        default = NA),
         qpcr_lab = recode_values(qpcr_lab,
                                     "pitt" ~ "rz",
                                        "snarl" ~ "snarl",
                                        default = NA),
         src = "snarl")
# %>%
#   inner_join(rz_snarl_ct, by = c("bd_swab_id", "extraction_lab", "qpcr_lab"))

frog_lookup = snarl_clean %>%
  select(frog_num,
         bd_swab_id,
         species_capture,
         collect_lab) %>%
  distinct()


rz_clean = rz_db %>%
  rename(bd_swab_id = sample_name_bd,
         bd_quant_cycle = bd_cycle_quant,
         bd_start_quant = bd_target_quant,
         bd_load = bd_its1_copies_per_swab,
         notes = comments_qpcr) %>%
  mutate(extraction_method = recode_values(extraction_kit,
                                           "qiagen_dneasy" ~ "qiagen",
                                           default = extraction_kit),
         src = "db") %>%
  left_join(frog_lookup, by = "bd_swab_id") %>%
  select(all_of(colnames(snarl_clean)))

alligned_clean = bind_rows(snarl_clean,
                           rz_clean) %>%
  mutate(bd_start_quant = if_else(is.na(bd_start_quant),
                                  0,
                                  bd_start_quant),
         correction_ratio = bd_load / bd_start_quant) %>%
  arrange(frog_num,
          extraction_lab,
          qpcr_lab)

```


```{r}
#| fig-width: 5
#| fig-height: 5

nice <- c(rz_rz = "RZ-RZ", rz_snarl = "RZ-SNARL",
          snarl_rz = "SNARL-RZ", snarl_snarl = "SNARL-SNARL")

# One row per panel; x/y orientation is set here
pairs <- tribble(
  ~letter, ~xvar,      ~yvar,
  "A",     "rz_rz",    "rz_snarl",
  "B",     "snarl_rz", "snarl_snarl",
  "C",     "rz_rz",    "snarl_rz",     # flipped from your version
  "D",     "rz_snarl", "snarl_snarl",
  "E",     "rz_rz",    "snarl_snarl"   # flipped from your version
)

# Stack all pairs into one long data frame
plot_df <- pmap_dfr(pairs, function(letter, xvar, yvar) {
  xv <- dat[[xvar]]
  yv <- dat[[yvar]]
  tibble(letter = letter, xvar = xvar, yvar = yvar, x = xv, y = yv)
}) %>%
  filter(!is.na(x), !is.na(y)) %>%
  mutate(xvar = factor(nice[xvar], levels = nice[1:3]),
         yvar = factor(nice[yvar], levels = nice[2:4]))

# Per-panel stats (on raw loads)
stats_df <- plot_df %>%
  group_by(letter, xvar, yvar) %>%
  summarise(n = n(), n_pos = sum(x > 0 & y > 0), .groups = "drop") %>%
  mutate(label = paste0("n = ", n, "\nboth > 0: ", n_pos))

ggplot(plot_df, aes(log10(x + 1), log10(y + 1))) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", colour = "grey50") +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm") +
  geom_text(data = stats_df, aes(x = -Inf, y = Inf, label = letter),
            hjust = -0.6, vjust = 1.4, fontface = "bold", size = 5,
            inherit.aes = FALSE) +
  geom_text(data = stats_df, aes(x = Inf, y = -Inf, label = label),
            hjust = 1.05, vjust = -0.3, size = 2.75, lineheight = 0.9,
            inherit.aes = FALSE) +
  facet_grid(xvar ~ yvar, switch = "both") +
  coord_fixed() +
  labs(x = "log10(Bd load + 1)  [extraction lab – qPCR lab]",
       y = "log10(Bd load + 1)  [extraction lab – qPCR lab]") +
  theme_bw() +
  theme(strip.placement = "outside",
        strip.background = element_blank(),
        strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank())

```